# Form implementation generated from reading ui file './ui/departurewindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generatedAt = QtWidgets.QLabel(parent=self.centralwidget)
        self.generatedAt.setObjectName("generatedAt")
        self.verticalLayout.addWidget(self.generatedAt)
        self.serviceCount = QtWidgets.QLabel(parent=self.centralwidget)
        self.serviceCount.setObjectName("serviceCount")
        self.verticalLayout.addWidget(self.serviceCount)
        self.stationName = QtWidgets.QLabel(parent=self.centralwidget)
        self.stationName.setObjectName("stationName")
        self.verticalLayout.addWidget(self.stationName)
        self.departureBoard = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.departureBoard.setObjectName("departureBoard")
        self.departureBoard.setColumnCount(5)
        self.departureBoard.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.departureBoard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.departureBoard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.departureBoard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.departureBoard.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.departureBoard.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.departureBoard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generatedAt.setText(_translate("MainWindow", "Generated At:"))
        self.serviceCount.setText(_translate("MainWindow", "Service Count: "))
        self.stationName.setText(_translate("MainWindow", "Station Name: "))
        item = self.departureBoard.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Departure Time"))
        item = self.departureBoard.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.departureBoard.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Operator"))
        item = self.departureBoard.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Coaches"))
        item = self.departureBoard.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Service GUID"))
