# Form implementation generated from reading ui file './ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stationTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.stationTable.setObjectName("stationTable")
        self.stationTable.setColumnCount(1)
        self.stationTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.stationTable.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.stationTable)
        self.showDepartureBoard = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Hasklig")
        font.setPointSize(16)
        self.showDepartureBoard.setFont(font)
        self.showDepartureBoard.setObjectName("showDepartureBoard")
        self.verticalLayout.addWidget(self.showDepartureBoard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.stationTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Station"))
        self.showDepartureBoard.setText(_translate("MainWindow", "Departure Board"))
